[2023-12-03 17:12:25,335] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.17.0.2:5000 - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:12:25,422] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:12:33,533] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:12:33] "[31m[1mPOST /doce HTTP/1.1[0m" 409 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:12:47,131] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.17.0.2:5000 - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:12:47,141] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:12:49,600] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:12:49] "[31m[1mPOST /doce HTTP/1.1[0m" 409 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:13:48,392] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.17.0.2:5000 - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:13:48,403] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:13:51,533] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:13:51] "POST /doce HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:13:53,598] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:13:53] "GET /doces HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:14:24,733] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:14:24] "GET /doces HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:14:52,988] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:14:52] "GET /images/F_UTD4xWYAAdStq.jpg HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:15:08,473] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:15:08] "GET /doces HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:15:08,902] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:15:08] "GET /images/F_UTD4xWYAAdStq.jpg HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:15:08,956] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:15:08] "[33mGET /%20/minhas%20imagens HTTP/1.1[0m" 404 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:15:09,022] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:15:09] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:15:09,364] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:15:09] "[32mGET /openapi HTTP/1.1[0m" 308 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:15:09,669] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:15:09] "GET /openapi/ HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:15:47,654] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:15:47] "GET /doce?id=3 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:15:50,175] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:15:50] "OPTIONS /doce?descricao=Cupcake%20XXX HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:15:50,288] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:15:50] "POST /avaliacao HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:15:50,543] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:15:50] "DELETE /doce?descricao=Cupcake%20XXX HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:15:52,690] WARNING get_doce() L137  Erro ao buscar doce '3', Doce n√£o encontrado na base :/ - call_trace=/workspaces/Api_confeitaria_backend-master/app.py L137 
[2023-12-03 17:15:52,691] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:15:52] "[33mGET /doce?id=3 HTTP/1.1[0m" 404 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:15:53,887] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:15:53] "GET /doces HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:15:54,245] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:15:54] "[33mGET /%20/minhas%20imagens HTTP/1.1[0m" 404 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:15:54,283] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:15:54] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:15:54,578] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:15:54] "GET /openapi/ HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:15:55,324] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:15:55] "GET /doce?id=4 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:15:57,160] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:15:57] "OPTIONS /doce?descricao=Cupcake%20XXXX HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:15:57,261] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:15:57] "POST /avaliacao HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:15:57,543] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:15:57] "DELETE /doce?descricao=Cupcake%20XXXX HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:15:59,350] WARNING get_doce() L137  Erro ao buscar doce '4', Doce n√£o encontrado na base :/ - call_trace=/workspaces/Api_confeitaria_backend-master/app.py L137 
[2023-12-03 17:15:59,353] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:15:59] "[33mGET /doce?id=4 HTTP/1.1[0m" 404 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:16:00,370] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:16:00] "GET /doces HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:16:00,753] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:16:00] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:16:00,784] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:16:00] "[33mGET /%20/minhas%20imagens HTTP/1.1[0m" 404 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:16:01,061] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:16:01] "GET /openapi/ HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:16:25,143] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:16:25] "GET /doces HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:16:25,519] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:16:25] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:16:25,588] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:16:25] "[33mGET /%20/minhas%20imagens HTTP/1.1[0m" 404 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:16:25,647] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:16:25] "[36mGET /images/F_UTD4xWYAAdStq.jpg HTTP/1.1[0m" 304 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:16:25,903] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:16:25] "GET /openapi/ HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:16:27,077] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:16:27] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:16:27,147] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:16:27] "GET /doce?id=27 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:16:27,414] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:16:27] "GET /openapi/ HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:16:29,083] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:16:29] "GET /doces HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
[2023-12-03 17:16:29,428] INFO _log() L96   127.0.0.1 - - [03/Dec/2023 17:16:29] "[33mGET /%20/minhas%20imagens HTTP/1.1[0m" 404 - - call_trace=/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py L96  
